# Generated by Django 3.0.6 on 2020-09-12 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_taskstate_color'),
        ('comments', '0002_commenttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.Task'),
        ),
        migrations.DeleteModel(
            name='CommentTask',
        ),
    ]
