# Generated by Django 3.0.6 on 2020-09-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20200912_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='start_at',
            field=models.DateField(auto_created=True, blank=True, editable=False, verbose_name='Дата создания'),
        ),
    ]
