# Generated by Django 3.0.6 on 2020-09-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_taskstate_color'),
        ('comments', '0007_remove_comment_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ManyToManyField(to='tasks.Task'),
        ),
    ]
