# Generated by Django 3.0.6 on 2020-05-17 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200518_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 18, 1, 18, 23, 742761), verbose_name='Дата создания'),
        ),
    ]
