# Generated by Django 3.0.6 on 2020-09-12 14:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('reports', '0002_reportstatus'),
        ('tasks', '0008_auto_20200518_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='area',
        ),
        migrations.AlterField(
            model_name='task',
            name='end_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 19, 17, 2, 55, 32460), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='report_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.ReportStatus', verbose_name='Статус отчетности'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 12, 17, 2, 55, 32460), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Subject', verbose_name='Субъект задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='dictionaries.Tag'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='ReportStatus',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
