# Generated by Django 3.0.6 on 2020-09-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_auto_20200912_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstate',
            name='color',
        ),
    ]
