# Generated by Django 3.0.6 on 2020-09-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_remove_taskstate_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstate',
            name='color',
            field=models.CharField(default='0277bd', max_length=6, verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
