# Generated by Django 3.0.6 on 2020-09-12 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_taskactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.TaskActivity'),
        ),
    ]
