# Generated by Django 3.0.6 on 2020-09-12 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportstatus'),
        ('tasks', '0029_auto_20200913_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='report_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.ReportStatus', verbose_name='Статус отчетности'),
        ),
    ]
