# Generated by Django 3.0.6 on 2020-09-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_auto_20200913_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на основной ресурс к задаче'),
        ),
    ]
