# Generated by Django 3.0.6 on 2020-09-12 14:02

import core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус отчетности',
                'verbose_name_plural': 'Статусы отчетности',
            },
            bases=(core.mixins.ModelStrMixin, models.Model),
        ),
    ]
