# Generated by Django 3.0.6 on 2020-05-11 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Область задач',
                'verbose_name_plural': 'Области задач',
            },
        ),
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус отчетности',
                'verbose_name_plural': 'Статусы отчетности',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Area')),
            ],
            options={
                'verbose_name': 'Субъект задач',
                'verbose_name_plural': 'Субъекты задач',
            },
        ),
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Название')),
                ('value', models.IntegerField(verbose_name='Целочисленное значение приоритета')),
            ],
            options={
                'verbose_name': 'Приоритет задач',
                'verbose_name_plural': 'Приоритеты задач',
            },
        ),
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Состояние задачи',
                'verbose_name_plural': 'Состояния задачи',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('details', models.TextField(default='', verbose_name='Детали задачи')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.TaskPriority')),
                ('report_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.ReportStatus')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.TaskState')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Subject')),
                ('tags', models.ManyToManyField(to='users.Tag')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
