# Generated by Django 3.0.6 on 2020-05-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_at',
            field=models.DateField(default='2020-05-05', verbose_name='Дата завершения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='start_at',
            field=models.DateField(auto_created=True, default='2020-05-05', verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
