# Generated by Django 3.0.6 on 2020-05-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200517_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
