# Generated by Django 3.0.6 on 2020-05-17 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200518_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstate',
            name='code',
            field=models.CharField(default='', max_length=2, verbose_name='Кодовое обозначение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='end_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 25, 2, 50, 46, 36451), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 18, 2, 50, 46, 36451), verbose_name='Дата создания'),
        ),
    ]
