# Generated by Django 3.0.6 on 2020-09-12 15:29

import colorfield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_auto_20200912_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstate',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 19, 18, 28, 59, 981784), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 12, 18, 28, 59, 981784), verbose_name='Дата создания'),
        ),
    ]
