# Generated by Django 3.0.6 on 2020-09-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_taskstate_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип активности по задаче',
                'verbose_name_plural': 'Типы активностей по задачам',
            },
        ),
    ]
