# Generated by Django 3.0.6 on 2020-09-12 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_auto_20200913_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='activity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.TaskActivity', verbose_name='Активность'),
        ),
    ]
