# Generated by Django 3.0.6 on 2020-09-12 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_auto_20200913_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.TaskActivity', verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.TaskPriority', verbose_name='Приоритет'),
        ),
    ]
