# Generated by Django 3.0.6 on 2020-09-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20200912_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='start_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
