# Generated by Django 3.0.6 on 2020-09-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватар пользователя'),
        ),
    ]
