# Generated by Django 3.0.6 on 2020-09-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200913_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student', models.BooleanField(verbose_name='Флаг: Является Студентом')),
                ('is_employee', models.BooleanField(verbose_name='Флаг: Является Сотрудником компании')),
                ('is_employer', models.BooleanField(verbose_name='Флаг: Является Учредителем компании')),
                ('is_manager', models.BooleanField(verbose_name='Флаг: Является Менеджером')),
                ('is_freelancer', models.BooleanField(verbose_name='Флаг: Является Фрилансером')),
                ('rate', models.IntegerField(verbose_name='Оценка сервиса')),
            ],
            options={
                'verbose_name': 'Анкета от пользователя',
                'verbose_name_plural': 'Анкеты от пользователей',
            },
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='gallery', verbose_name='Аватар пользователя'),
        ),
    ]
