# Generated by Django 3.0.6 on 2020-09-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200913_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurvey',
            name='is_employee',
            field=models.BooleanField(verbose_name='Являюсь Сотрудником компании'),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='is_employer',
            field=models.BooleanField(verbose_name='Являюсь Учредителем компании'),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='is_freelancer',
            field=models.BooleanField(verbose_name='Являюсь Фрилансером'),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='is_manager',
            field=models.BooleanField(verbose_name='Являюсь Менеджером'),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='is_student',
            field=models.BooleanField(verbose_name='Являюсь Студентом'),
        ),
    ]
